# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-08 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
